# Generated by Django 6.0.7 on 2026-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
