# Generated by Django 6.0.7 on 2026-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
