# Generated by Django 6.0.7 on 2026-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_developer_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
