# Generated by Django 5.2.4 on 2026-08-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0006_developer_owner_alter_developer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='developer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
